# Assignment Questions

# Section A: Data Structures & Control Structures

In [16]:
c = []
print(type(c))

<class 'list'>


In [17]:
c = [2,8,12,18,25,36,45,"True"]
print(c)

[2, 8, 12, 18, 25, 36, 45, 'True']


In [18]:
c.append("kiran")
print(c)

[2, 8, 12, 18, 25, 36, 45, 'True', 'kiran']


In [19]:
c.extend([17,26,62,79,"False"])
print(c)

[2, 8, 12, 18, 25, 36, 45, 'True', 'kiran', 17, 26, 62, 79, 'False']


In [20]:
c.insert(0,"xyz")
print(c)

['xyz', 2, 8, 12, 18, 25, 36, 45, 'True', 'kiran', 17, 26, 62, 79, 'False']


In [23]:
c.remove(12)
print(c)

['xyz', 2, 18, 25, 36, 45, 'True', 'kiran', 17, 26, 62, 79, 'False']


In [24]:
c.pop(4)

36

In [30]:
c.index(18)

2

In [35]:
c.clear()
print(c)

[]


In [36]:
c.count(2)

0

In [44]:
c = [2,8,12,18,25,4,6,45]
c.sort()
print(c)

[2, 4, 6, 8, 12, 18, 25, 45]


In [60]:
c = [2,8,12,18,25,4,6,45]
c.reverse()
print(c[1])

6


In [63]:
s1 = ("uday","kiran","sai") #TypeError: 'tuple' object does not support item assignment
s1[1]="hari"
print(c[1])

TypeError: 'tuple' object does not support item assignment

In [65]:
s = {}
print(type(s))

<class 'dict'>


In [66]:
s = {2,25,2,6,2,8,36,2} # set is does not allow the duplicate values.unordered output elements 
print(s)

{2, 36, 6, 8, 25}


In [67]:
D = {}
print(type(D))

<class 'dict'>


In [69]:
D = {"Name":"Hari","Age":23,"City":"hyderabad"}
D["Age"]=25
D["Email"]="hari@gmail.com"
print(D)

{'Name': 'Hari', 'Age': 25, 'City': 'hyderabad', 'Email': 'hari@gmail.com'}


In [98]:
age = 18
if age>18:
    print("eligible to vote")
elif age ==17:
    print("not eligible to vote")
else:
    print("eligible to vote")

eligible to vote


In [99]:
marks = 82  # change the value to test

if marks >= 90:
    print("A")
elif marks >= 75:
    print("B")
elif marks >= 50:
    print("C")
else:
    print("Fail")

B


In [100]:
number = 8  # you can change this to test

if number > 0:
    if number % 2 == 0:
        print("The number is positive and even.")
    else:
        print("The number is positive but not even.")
elif number == 0:
    print("The number is zero.")
else:
    print("The number is negative.")

The number is positive and even.


# Section B: Numpy

In [107]:
import numpy as np

# Scalar
scalar = np.array(5)
print("Scalar:")
print(scalar)

# 1D array with values 1 to 5
array_1d = np.array([1, 2, 3, 4, 5])
print("\n1D Array:")
print(array_1d)

# 2D array (2x3) with values from 10 to 60 in steps of 10
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60]])
print("\n2D Array:")
print(array_2d)

Scalar:
5

1D Array:
[1 2 3 4 5]

2D Array:
[[10 20 30]
 [40 50 60]]


In [102]:
import numpy as np

# Generate a 4x4 array of random integers between 0 and 100
random_array = np.random.randint(0, 101, size=(4, 4))

print("4x4 Random Array:")
print(random_array)

4x4 Random Array:
[[ 20 100  75  94]
 [ 25  32  57  60]
 [ 55   2  16  20]
 [ 82  41  98  21]]


In [108]:
import numpy as np
import pandas as pd

# Create a 3x3 NumPy array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Convert to pandas DataFrame and add column names
df = pd.DataFrame(array_2d, columns=['A', 'B', 'C'])

print("DataFrame:")
print(df)

DataFrame:
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9
